### ISSUE TITLE
Getting Fetal Error

### ISSUE THREAD

**Issue by faisal-calderalabs** [sheerid/getting-started#17]
Fatal error: Uncaught exception 'Exception' with message 'error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure' in localpath\htdocs\sheerid\SheerID.php:233 Stack trace: #0 localpath\htdocs\sheerid\SheerID.php(167): SheerIDRequest->execute() #1 localpath\htdocs\sheerid\SheerID.php(65): SheerID->post('/verification', Array) #2 localpath\htdocs\sheerid\military.php(35): SheerID->verify(Array) #3 {main} thrown in localpath\htdocs\sheerid\SheerID.php on line 233

solution please ???

**Comment by aboone** [comment]
The issue is this line, it should be removed:
https://github.com/sheerid/getting-started/blob/master/recipes/php/SheerID.php#L209

For PHP samples, I would recommend looking at https://github.com/sheerid/sheerid-php instead, it is more up to date than the PHP code contained in this project.
